import { prisma } from "@project-relay/database";
import { providerRegistry, type ProviderAuthentication, type ProviderId, type ProviderProbe } from "@project-relay/providers";
export type ProviderHealthMode="refresh"|"auth";
function rateLimited(message:string){return /rate.?limit|too many requests|429/i.test(message);}function networkError(message:string){return /network|enotfound|econnrefused|offline|timed out/i.test(message);}
export class ProviderHealthMonitor{private readonly active=new Set<string>();
  async probe(providerId:ProviderId,mode:ProviderHealthMode,force=false){const key=`${providerId}:${mode}`;if(this.active.has(key))return;this.active.add(key);try{await prisma.providerHealth.upsert({where:{providerId},create:{providerId},update:{}});const current=await prisma.providerHealth.findUniqueOrThrow({where:{providerId}});if(mode==="auth"&&!force&&current.lastAuthenticationCheck&&Date.now()-current.lastAuthenticationCheck.valueOf()<15*60_000)return;const claimed=await prisma.providerHealth.updateMany({where:{providerId,checkInProgress:false},data:{checkInProgress:true,checkStartedAt:new Date()}});if(!claimed.count)return;try{const provider=providerRegistry.get(providerId),probe=mode==="auth"?await provider.probeAuthentication():await provider.refreshHealth();await this.persist(probe,mode);await prisma.providerHealthCheck.create({data:{providerId,mode,authentication:probe.authentication,installed:probe.installed,available:probe.available,latencyMs:probe.latencyMs??null}});}finally{await prisma.providerHealth.update({where:{providerId},data:{checkInProgress:false,checkStartedAt:null}});}}finally{this.active.delete(key);}}
  private async persist(probe:ProviderProbe,mode:ProviderHealthMode){const existing=await prisma.providerHealth.findUnique({where:{providerId:probe.providerId}});const authentication=mode==="auth"?probe.authentication:existing?.authentication??"UNKNOWN";await prisma.providerHealth.update({where:{providerId:probe.providerId},data:{installed:probe.installed,version:probe.version??null,authentication,available:mode==="auth"?probe.available:probe.installed&&authentication==="AUTHENTICATED",latencyMs:probe.latencyMs??null,lastChecked:probe.checkedAt,...(mode==="auth"?{lastAuthenticationCheck:probe.checkedAt}:{}),...(authentication==="AUTHENTICATED"?{lastSuccessfulRequest:probe.checkedAt}:{}),...(authentication==="RATE_LIMITED"?{lastRateLimitResponse:probe.checkedAt}:{}),resetAt:probe.resetAt??existing?.resetAt??null,remainingPercent:probe.quotaExact?probe.remainingPercent??null:null,quotaSource:probe.quotaSource,quotaConfidence:probe.quotaConfidence,quotaExact:probe.quotaExact}});}
  async recordTaskResponse(providerId:string,success:boolean,message="",latencyMs?:number){if(!["codex-cli","claude-cli"].includes(providerId))return;const authentication:ProviderAuthentication=success?"AUTHENTICATED":rateLimited(message)?"RATE_LIMITED":networkError(message)?"NETWORK_ERROR":"CLI_ERROR",now=new Date();await prisma.providerHealth.upsert({where:{providerId},create:{providerId,installed:true,authentication,available:success,latencyMs:latencyMs??null,lastChecked:now,lastAuthenticationCheck:now,...(success?{lastSuccessfulRequest:now}:{}),...(authentication==="RATE_LIMITED"?{lastRateLimitResponse:now}:{})},update:{authentication,available:success,latencyMs:latencyMs??null,lastChecked:now,lastAuthenticationCheck:now,...(success?{lastSuccessfulRequest:now}:{}),...(authentication==="RATE_LIMITED"?{lastRateLimitResponse:now}:{})}});}
  async startup(){await prisma.providerHealth.updateMany({where:{checkInProgress:true},data:{checkInProgress:false,checkStartedAt:null}});await Promise.all(providerRegistry.list().map(provider=>this.probe(provider.id,"refresh",true)));}async refreshAll(){await Promise.all(providerRegistry.list().map(provider=>this.probe(provider.id,"refresh")));}async authenticateAll(){await Promise.all(providerRegistry.list().map(provider=>this.probe(provider.id,"auth")));}}
export const providerHealthMonitor=new ProviderHealthMonitor();
