CREATE TYPE "ConversationStatus" AS ENUM ('ACTIVE','PAUSED','COMPLETED','CANCELLED');
CREATE TYPE "ConversationRole" AS ENUM ('USER','ASSISTANT','SYSTEM','TOOL');
CREATE TYPE "ConversationMode" AS ENUM ('ASK','IMPLEMENT','REVIEW','CONTINUE','VERIFY');
CREATE TYPE "ConversationMessageStatus" AS ENUM ('QUEUED','RUNNING','COMPLETED','CANCELLED','FAILED');
CREATE TYPE "ProviderSessionStatus" AS ENUM ('QUEUED','RUNNING','COMPLETED','CANCELLED','FAILED');
CREATE TABLE "Conversation" ("id" TEXT NOT NULL,"projectId" TEXT NOT NULL,"title" TEXT NOT NULL,"status" "ConversationStatus" NOT NULL DEFAULT 'ACTIVE',"activeProviderId" TEXT,"currentCheckpointId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Conversation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ConversationMessage" ("id" TEXT NOT NULL,"conversationId" TEXT NOT NULL,"role" "ConversationRole" NOT NULL,"providerId" TEXT,"providerSessionId" TEXT,"mode" "ConversationMode" NOT NULL,"content" TEXT NOT NULL,"status" "ConversationMessageStatus" NOT NULL DEFAULT 'QUEUED',"handoffCapsuleId" TEXT,"taskId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ConversationMessage_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ProviderSession" ("id" TEXT NOT NULL,"conversationId" TEXT NOT NULL,"providerId" TEXT NOT NULL,"externalSessionId" TEXT,"status" "ProviderSessionStatus" NOT NULL DEFAULT 'QUEUED',"startedAt" TIMESTAMP(3),"endedAt" TIMESTAMP(3),"lastMessageId" TEXT,CONSTRAINT "ProviderSession_pkey" PRIMARY KEY ("id"));
CREATE TABLE "HandoffCapsule" ("id" TEXT NOT NULL,"conversationId" TEXT NOT NULL,"fromProviderId" TEXT NOT NULL,"toProviderId" TEXT NOT NULL,"version" INTEGER NOT NULL,"objective" TEXT NOT NULL,"relevantDecisions" JSONB NOT NULL,"filesChanged" JSONB NOT NULL,"gitBaseline" JSONB NOT NULL,"gitDiffSummary" TEXT NOT NULL,"tests" JSONB NOT NULL,"unresolvedIssues" JSONB NOT NULL,"acceptedFindings" JSONB NOT NULL,"sourceMessageRange" JSONB NOT NULL,"checksum" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "HandoffCapsule_pkey" PRIMARY KEY ("id"));
CREATE TABLE "RoutingDecision" ("id" TEXT NOT NULL,"conversationId" TEXT NOT NULL,"requestedProviderId" TEXT,"selectedProviderId" TEXT NOT NULL,"reason" TEXT NOT NULL,"providerHealthSnapshot" JSONB NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "RoutingDecision_pkey" PRIMARY KEY ("id"));
ALTER TABLE "Conversation" ADD CONSTRAINT "Conversation_projectId_fkey" FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ConversationMessage" ADD CONSTRAINT "ConversationMessage_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "Conversation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProviderSession" ADD CONSTRAINT "ProviderSession_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "Conversation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "HandoffCapsule" ADD CONSTRAINT "HandoffCapsule_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "Conversation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RoutingDecision" ADD CONSTRAINT "RoutingDecision_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "Conversation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE INDEX "Conversation_projectId_updatedAt_idx" ON "Conversation"("projectId","updatedAt");
CREATE INDEX "ConversationMessage_conversationId_createdAt_idx" ON "ConversationMessage"("conversationId","createdAt");
CREATE INDEX "ProviderSession_conversationId_providerId_startedAt_idx" ON "ProviderSession"("conversationId","providerId","startedAt");
CREATE UNIQUE INDEX "HandoffCapsule_conversationId_version_key" ON "HandoffCapsule"("conversationId","version");
CREATE INDEX "RoutingDecision_conversationId_createdAt_idx" ON "RoutingDecision"("conversationId","createdAt");
