import { createHash } from "node:crypto";
import { NextResponse } from "next/server";
import { Prisma, prisma } from "@project-relay/database";
import { inspectGit } from "@project-relay/execution";
import { providerRegistry, type ProviderId } from "@project-relay/providers";
import { approximateTokens, compactReviewCapsule, findLockedDecisionConflicts, type TaskCapsuleContent } from "@project-relay/shared";
import { ApiError, apiErrorResponse } from "../../../lib/api-errors";
import { getSessionQueue } from "../../../lib/redis";
type Purpose="IMPLEMENTATION"|"REVIEW"|"VERIFICATION";type Selection="AUTO"|ProviderId;
async function selectProvider(purpose:Purpose,selection:Selection,defaultProvider:string){const allowed:ProviderId[]=purpose==="IMPLEMENTATION"?["codex-cli"]:["claude-cli"];if(selection!=="AUTO"&&!allowed.includes(selection))throw new ApiError("VALIDATION_ERROR",`${selection} is not permitted for ${purpose.toLowerCase()} sessions.`);const health=await prisma.providerHealth.findMany({where:{providerId:{in:allowed}}});const byId=new Map(health.map(item=>[item.providerId,item]));if(selection!=="AUTO"){const item=byId.get(selection);return{providerId:selection,health:item};}const preferred=allowed.includes(defaultProvider as ProviderId)?defaultProvider as ProviderId:allowed[0]!;const candidates=[preferred,...allowed.filter(id=>id!==preferred)];const providerId=candidates.find(id=>{const item=byId.get(id);return item?.available&&item.authentication!=="RATE_LIMITED";});if(!providerId)throw new ApiError("CONFLICT","No available provider for Auto selection. Refresh provider health or select a configured provider manually.");return{providerId,health:byId.get(providerId)};}
export async function POST(request:Request){try{const{taskId,purpose="IMPLEMENTATION",selection="AUTO",resumeSessionId}=await request.json()as{taskId?:string;purpose?:Purpose;selection?:Selection;resumeSessionId?:string};if(!taskId)throw new ApiError("VALIDATION_ERROR","taskId is required.");const task=await prisma.task.findUnique({where:{id:taskId},include:{capsules:{orderBy:{createdAt:"desc"},take:1},project:{include:{decisions:{where:{status:"ACCEPTED",locked:true}}}},reviewFindings:true}});if(!task||!task.capsules[0])throw new ApiError("VALIDATION_ERROR","Task and capsule are required.");if(purpose==="REVIEW"&&task.reviewRounds>=2)throw new ApiError("CONFLICT","Maximum of two review rounds reached.");if(purpose==="VERIFICATION"&&task.reviewFindings.some(f=>f.status==="PENDING"))throw new ApiError("CONFLICT","Accept or reject all current findings before verification.");if(purpose==="IMPLEMENTATION"&&task.parentTaskId&&task.remediationAttempts>=2)throw new ApiError("CONFLICT","Maximum of two remediation attempts reached.");const routing=await selectProvider(purpose,selection,task.project.defaultProvider);providerRegistry.get(routing.providerId);
  const conflicts=findLockedDecisionConflicts(task.project.decisions.map(d=>({id:d.id,forbiddenPaths:d.forbiddenPaths as string[],requiredPatterns:d.requiredPatterns as string[]})),task.relevantFiles as string[]);if(conflicts.length){await prisma.task.update({where:{id:task.id},data:{status:"BLOCKED"}});await prisma.auditEvent.create({data:{projectId:task.projectId,actor:"project-relay",action:"LOCKED_DECISION_CONFLICT",details:{taskId:task.id,conflicts}}});throw new ApiError("CONFLICT",`Task conflicts with locked decisions: ${conflicts.join("; ")}`);}
  const git=await inspectGit(task.project.repositoryPath),baselineDiffHash=createHash("sha256").update(`${git.commit}\n${git.status}\n${git.diff}`).digest("hex"),resume=resumeSessionId?await prisma.agentSession.findFirst({where:{id:resumeSessionId,taskId:task.id,providerId:routing.providerId}}):null;let capsuleId=task.capsules[0].id;if(purpose!=="IMPLEMENTATION"){const compact=compactReviewCapsule(task.capsules[0].content as TaskCapsuleContent);const capsule=await prisma.taskCapsule.create({data:{taskId:task.id,content:compact as Prisma.InputJsonValue,approximateTokenCount:approximateTokens(compact)}});capsuleId=capsule.id;}
  const session=await prisma.agentSession.create({data:{projectId:task.projectId,taskId:task.id,providerId:routing.providerId,state:"QUEUED",purpose,readOnly:purpose!=="IMPLEMENTATION",baselineCommit:git.commit,baselineDiffHash,...(resume?.externalId?{externalId:resume.externalId}:{})}});await prisma.$transaction([prisma.task.update({where:{id:task.id},data:{status:"IN_PROGRESS",activeSessionId:session.id,...(purpose==="REVIEW"?{reviewRounds:{increment:1}}:{}),...(purpose==="IMPLEMENTATION"&&task.parentTaskId?{remediationAttempts:{increment:1}}:{})}}),prisma.auditEvent.create({data:{projectId:task.projectId,actor:"local-user",action:"SESSION_QUEUED",details:{sessionId:session.id,taskId:task.id,providerId:routing.providerId,purpose,selection,quotaSource:routing.health?.quotaSource??"CLI_STATUS",quotaConfidence:routing.health?.quotaConfidence??"LOW",quotaExact:routing.health?.quotaExact??false,authentication:routing.health?.authentication??"UNKNOWN"}}})]);await getSessionQueue().add("run",{sessionId:session.id,taskId:task.id,capsuleId},{jobId:session.id,removeOnComplete:100,removeOnFail:100});
  // Never return AgentSession.externalId (the provider CLI's own session/thread id) to the browser.
  return NextResponse.json({id:session.id,taskId:session.taskId,providerId:session.providerId,state:session.state,purpose:session.purpose},{status:202});
}catch(error){return apiErrorResponse(error,"POST /api/sessions");}}
