import { createHash } from "node:crypto";
import { NextResponse } from "next/server";
import { Prisma, prisma } from "@project-relay/database";
import { inspectGit } from "@project-relay/execution";
import { providerRegistry } from "@project-relay/providers";
import { approximateTokens, compactReviewCapsule, findLockedDecisionConflicts, type TaskCapsuleContent } from "@project-relay/shared";
import { getSessionQueue } from "../../../lib/redis";
type Purpose="IMPLEMENTATION"|"REVIEW"|"VERIFICATION";
export async function POST(request:Request){try{
  const{taskId,purpose="IMPLEMENTATION",resumeSessionId}=await request.json()as{taskId?:string;purpose?:Purpose;resumeSessionId?:string};if(!taskId)throw new Error("taskId is required.");
  const task=await prisma.task.findUnique({where:{id:taskId},include:{capsules:{orderBy:{createdAt:"desc"},take:1},project:{include:{decisions:{where:{status:"ACCEPTED",locked:true}}}},reviewFindings:true}});if(!task||!task.capsules[0])throw new Error("Task and capsule are required.");
  if(purpose==="REVIEW"&&task.reviewRounds>=2)return NextResponse.json({error:"Maximum of two review rounds reached."},{status:409});if(purpose==="VERIFICATION"&&task.reviewFindings.some(f=>f.status==="PENDING"))return NextResponse.json({error:"Accept or reject all current findings before verification."},{status:409});if(purpose==="IMPLEMENTATION"&&task.parentTaskId&&task.remediationAttempts>=2)return NextResponse.json({error:"Maximum of two remediation attempts reached."},{status:409});
  const providerId=purpose==="IMPLEMENTATION"?task.assignedProvider:"claude-cli";providerRegistry.get(providerId);
  const conflicts=findLockedDecisionConflicts(task.project.decisions.map(d=>({id:d.id,forbiddenPaths:d.forbiddenPaths as string[],requiredPatterns:d.requiredPatterns as string[]})),task.relevantFiles as string[]);if(conflicts.length){await prisma.task.update({where:{id:task.id},data:{status:"BLOCKED"}});await prisma.auditEvent.create({data:{projectId:task.projectId,actor:"project-relay",action:"LOCKED_DECISION_CONFLICT",details:{taskId:task.id,conflicts}}});return NextResponse.json({error:`Task conflicts with locked decisions: ${conflicts.join("; ")}`},{status:409});}
  const git=await inspectGit(task.project.repositoryPath);const baselineDiffHash=createHash("sha256").update(`${git.commit}\n${git.status}\n${git.diff}`).digest("hex");const resume=resumeSessionId?await prisma.agentSession.findFirst({where:{id:resumeSessionId,taskId:task.id,providerId}}):null;
  let capsuleId=task.capsules[0].id;if(purpose!=="IMPLEMENTATION"){const compact=compactReviewCapsule(task.capsules[0].content as TaskCapsuleContent);const capsule=await prisma.taskCapsule.create({data:{taskId:task.id,content:compact as Prisma.InputJsonValue,approximateTokenCount:approximateTokens(compact)}});capsuleId=capsule.id;}
  const session=await prisma.agentSession.create({data:{projectId:task.projectId,taskId:task.id,providerId,state:"QUEUED",purpose,readOnly:purpose!=="IMPLEMENTATION",baselineCommit:git.commit,baselineDiffHash,...(resume?.externalId?{externalId:resume.externalId}:{})}});
  await prisma.$transaction([prisma.task.update({where:{id:task.id},data:{status:"IN_PROGRESS",activeSessionId:session.id,...(purpose==="REVIEW"?{reviewRounds:{increment:1}}:{}),...(purpose==="IMPLEMENTATION"&&task.parentTaskId?{remediationAttempts:{increment:1}}:{})}}),prisma.auditEvent.create({data:{projectId:task.projectId,actor:"local-user",action:"SESSION_QUEUED",details:{sessionId:session.id,taskId:task.id,providerId,purpose}}})]);await getSessionQueue().add("run",{sessionId:session.id,taskId:task.id,capsuleId},{jobId:session.id,removeOnComplete:100,removeOnFail:100});return NextResponse.json(session,{status:202});
}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Could not start session."},{status:400});}}
