import crossSpawn from "cross-spawn";
import { randomUUID } from "node:crypto";
import { spawn as nodeSpawn, type ChildProcess } from "node:child_process";
import { SAFE_ENVIRONMENT, StreamSafeRedactor, validateWorkspace } from "@project-relay/execution";
import type { TaskCapsuleContent } from "@project-relay/shared";
import { resolveCliExecutable, type ResolvedExecutable } from "./executable.js";

export type ProviderId="codex-cli"|"claude-cli";export type ProviderRole="IMPLEMENTER"|"REVIEWER"|"VERIFIER";
export type ProviderAuthentication="AUTHENTICATED"|"NOT_AUTHENTICATED"|"RATE_LIMITED"|"NETWORK_ERROR"|"CLI_ERROR"|"UNKNOWN";
export type QuotaSource="CLI_STATUS"|"PROVIDER_RESPONSE"|"LOCAL_ESTIMATE"|"USER_INPUT"|"OFFICIAL_API";
export type ProviderProbe={providerId:ProviderId;installed:boolean;version?:string;authentication:ProviderAuthentication;available:boolean;latencyMs?:number;checkedAt:Date;resetAt?:Date;remainingPercent?:number;quotaSource:QuotaSource;quotaConfidence:"LOW"|"MEDIUM"|"HIGH";quotaExact:boolean;markerObserved?:boolean;exitCode?:number|null};
export type ExecutionCapability="READ_ONLY"|"WORKSPACE_WRITE";
export type AgentSessionInput={workspace:string;taskId:string;capability:ExecutionCapability;role?:ProviderRole;resumeExternalId?:string};export type AgentSession={id:string;providerId:ProviderId;workspace:string;taskId:string;role:ProviderRole;capability:ExecutionCapability;externalId?:string};export type AgentEvent={type:"state"|"stdout"|"stderr"|"usage";message:string;timestamp:Date};export type UsageReport={estimated:boolean;inputTokens?:number;outputTokens?:number;costUsd?:number};export type ConnectionTest={ok:boolean;output:string;durationMs:number;probe:ProviderProbe;markerObserved:boolean;exitCode:number|null};
export interface CodingProvider{readonly id:ProviderId;readonly name:string;readonly defaultRoles:ProviderRole[];readonly setupInstructions:string;detectInstallation():Promise<boolean>;getVersion():Promise<string|undefined>;refreshHealth():Promise<ProviderProbe>;probeAuthentication(signal?:AbortSignal):Promise<ProviderProbe>;testConnection(signal?:AbortSignal):Promise<ConnectionTest>;createSession(input:AgentSessionInput):Promise<AgentSession>;startSession(session:AgentSession,capsule:TaskCapsuleContent,signal?:AbortSignal):Promise<void>;sendTask(session:AgentSession,capsule:TaskCapsuleContent,signal?:AbortSignal):Promise<void>;streamEvents(sessionId:string):AsyncIterable<AgentEvent>;cancelSession(sessionId:string):Promise<void>;resumeSession(session:AgentSession,capsule:TaskCapsuleContent,signal?:AbortSignal):Promise<void>;getUsage(sessionId:string):Promise<UsageReport>;}
type SpawnFn=typeof crossSpawn;type Resolver=(command:"codex"|"claude")=>Promise<ResolvedExecutable|undefined>;type SessionRecord={events:AgentEvent[];waiters:Array<()=>void>;controller:AbortController;usage:UsageReport;child?:ChildProcess;complete:boolean};type ProcessResult={code:number|null;output:string;durationMs:number;timedOut:boolean;cancelled:boolean;error?:string};
function classify(output:string,code:number|null,marker:string,result:Pick<ProcessResult,"timedOut"|"cancelled"|"error">):ProviderAuthentication{const text=output.toLowerCase();if(result.cancelled||result.timedOut)return"UNKNOWN";if(/rate.?limit|too many requests|429/.test(text))return"RATE_LIMITED";if(/network|enotfound|econnrefused|timed out|offline/.test(text))return"NETWORK_ERROR";if(code===0&&output.includes(marker))return"AUTHENTICATED";if(/not (logged|authenticated)|login|auth(?:entication)? required|unauthorized|forbidden|401/.test(text))return"NOT_AUTHENTICATED";return result.error||code!==0?"CLI_ERROR":"UNKNOWN";}
export function classifyProviderProbe(output:string,code:number|null,marker:string,result:Pick<ProcessResult,"timedOut"|"cancelled"|"error">){return classify(output,code,marker,result);}
function resetAtFrom(output:string):Date|undefined{for(const line of output.split("\n")){try{const value=JSON.parse(line)as{reset_at?:string;resetAt?:string};const raw=value.reset_at??value.resetAt;if(raw){const date=new Date(raw);if(!Number.isNaN(date.valueOf()))return date;}}catch{}}return undefined;}
function killProcessTree(child:ChildProcess){if(process.platform==="win32"&&child.pid){const killer=nodeSpawn("taskkill",["/pid",String(child.pid),"/t","/f"],{shell:false,windowsHide:true,env:SAFE_ENVIRONMENT});killer.unref();}else child.kill();}
abstract class CliProvider implements CodingProvider{
  abstract readonly id:ProviderId;abstract readonly name:string;abstract readonly command:"codex"|"claude";abstract readonly defaultRoles:ProviderRole[];abstract readonly setupInstructions:string;protected readonly sessions=new Map<string,SessionRecord>();private resolved:ResolvedExecutable|undefined;
  constructor(protected readonly spawnProcess:SpawnFn=crossSpawn,private readonly resolver:Resolver=resolveCliExecutable){}
  protected async resolve(){if(!this.resolved)this.resolved=await this.resolver(this.command);return this.resolved;}
  protected async execute(args:string[],input?:string,signal?:AbortSignal,timeoutMs=30_000,maxBytes=32_768):Promise<ProcessResult>{const executable=await this.resolve();if(!executable)return{code:null,output:"",durationMs:0,timedOut:false,cancelled:false,error:"CLI_NOT_FOUND"};const started=Date.now(),redactor=new StreamSafeRedactor(maxBytes);return await new Promise(resolve=>{let child:ChildProcess;try{child=this.spawnProcess(executable.canonicalPath,args,{shell:false,windowsHide:true,env:SAFE_ENVIRONMENT});}catch(error){resolve({code:null,output:"",durationMs:Date.now()-started,timedOut:false,cancelled:false,error:error instanceof Error?error.message:"CLI spawn failed"});return;}let timedOut=false,cancelled=false,error:string|undefined;child.stdout?.on("data",(chunk:Buffer)=>redactor.append(chunk));child.stderr?.on("data",(chunk:Buffer)=>redactor.append(chunk));child.once("error",event=>{error=event.message;});const stop=()=>{cancelled=true;killProcessTree(child);};signal?.addEventListener("abort",stop,{once:true});const timer=setTimeout(()=>{timedOut=true;killProcessTree(child);},timeoutMs);child.once("close",code=>{clearTimeout(timer);signal?.removeEventListener("abort",stop);resolve({code,output:redactor.flush(),durationMs:Date.now()-started,timedOut,cancelled,...(error?{error}:{})});});child.stdin?.end(input);});}
  async detectInstallation(){return Boolean(await this.resolve());}async getVersion(){const result=await this.execute(["--version"],undefined,undefined,10_000);return result.code===0?result.output.trim():undefined;}
  async refreshHealth():Promise<ProviderProbe>{const checkedAt=new Date();const installed=await this.detectInstallation();const version=installed?await this.getVersion():undefined;return{providerId:this.id,installed,...(version?{version}:{}),authentication:"UNKNOWN",available:installed,checkedAt,quotaSource:"CLI_STATUS",quotaConfidence:"LOW",quotaExact:false};}
  protected abstract authCommand():{args:string[];prompt:string;marker:string};
  async probeAuthentication(signal?:AbortSignal):Promise<ProviderProbe>{const checkedAt=new Date(),command=this.authCommand(),result=await this.execute(command.args,command.prompt,signal,60_000,16_384),authentication=classify(result.output,result.code,command.marker,result);const installed=await this.detectInstallation();const resetAt=resetAtFrom(result.output);return{providerId:this.id,installed,authentication,available:authentication==="AUTHENTICATED",...(result.durationMs?{latencyMs:result.durationMs}:{}),checkedAt,markerObserved:result.output.includes(command.marker),exitCode:result.code,...(resetAt?{resetAt}:{}),quotaSource:"CLI_STATUS",quotaConfidence:"LOW",quotaExact:false};}
  async testConnection(signal?:AbortSignal){const probe=await this.probeAuthentication(signal);return{ok:probe.authentication==="AUTHENTICATED",output:"Provider probe completed; inspect persisted health status for details.",durationMs:probe.latencyMs??0,markerObserved:probe.markerObserved===true,exitCode:probe.exitCode??null,probe};}
  protected supportsCapability(_capability:ExecutionCapability):boolean{return true;}
  async createSession(input:AgentSessionInput){if(!this.supportsCapability(input.capability))throw new Error(`${this.name} does not support ${input.capability} execution.`);const workspace=await validateWorkspace(input.workspace);const session:AgentSession={id:randomUUID(),providerId:this.id,workspace,taskId:input.taskId,role:input.role??this.defaultRoles[0]!,capability:input.capability,...(input.resumeExternalId?{externalId:input.resumeExternalId}:{})};this.sessions.set(session.id,{events:[],waiters:[],controller:new AbortController(),usage:{estimated:true},complete:false});return session;}
  protected prompt(session:AgentSession,capsule:TaskCapsuleContent){return[`Role: ${session.role}.`,`Use only supplied structured state and report evidence.`,JSON.stringify(capsule,null,2)].join("\n\n");}protected abstract sessionCommand(session:AgentSession,resume:boolean):string[];
  async startSession(session:AgentSession,capsule:TaskCapsuleContent,signal?:AbortSignal){await this.runSession(session,capsule,false,signal);}async sendTask(session:AgentSession,capsule:TaskCapsuleContent,signal?:AbortSignal){await this.startSession(session,capsule,signal);}async resumeSession(session:AgentSession,capsule:TaskCapsuleContent,signal?:AbortSignal){await this.runSession(session,capsule,true,signal);}
  private async runSession(session:AgentSession,capsule:TaskCapsuleContent,resume:boolean,signal?:AbortSignal){const record=this.sessions.get(session.id);if(!record)throw new Error("Unknown provider session.");const prompt=this.prompt(session,capsule),executable=await this.resolve();if(!executable)throw new Error(`${this.name} CLI is not installed.`);record.usage={estimated:true,inputTokens:Math.ceil(prompt.length/4),outputTokens:0};const effective=signal??record.controller.signal;await new Promise<void>((resolve,reject)=>{const child=this.spawnProcess(executable.canonicalPath,this.sessionCommand(session,resume),{cwd:session.workspace,shell:false,windowsHide:true,env:SAFE_ENVIRONMENT});record.child=child;const out=new StreamSafeRedactor(262_144),err=new StreamSafeRedactor(65_536);child.stdout?.on("data",(chunk:Buffer)=>out.append(chunk));child.stderr?.on("data",(chunk:Buffer)=>err.append(chunk));const abort=()=>killProcessTree(child);effective.addEventListener("abort",abort,{once:true});child.once("error",reject);child.once("close",code=>{effective.removeEventListener("abort",abort);for(const[type,message]of[["stdout",out.flush()],["stderr",err.flush()]]as const)if(message){record.events.push({type,message,timestamp:new Date()});record.usage.outputTokens=(record.usage.outputTokens??0)+Math.ceil(message.length/4);}record.complete=true;record.waiters.splice(0).forEach(wake=>wake());if(code===0)resolve();else reject(new Error(`${this.name} exited with code ${String(code)}.`));});child.stdin?.end(prompt);});}
  async*streamEvents(sessionId:string){const record=this.sessions.get(sessionId);if(!record)throw new Error("Unknown provider session.");let cursor=0;while(!record.complete||cursor<record.events.length){while(cursor<record.events.length)yield record.events[cursor++]!;if(!record.complete)await new Promise<void>(resolve=>record.waiters.push(resolve));}}async cancelSession(sessionId:string){const record=this.sessions.get(sessionId);if(!record)return;record.controller.abort();if(record.child)killProcessTree(record.child);record.complete=true;record.waiters.splice(0).forEach(wake=>wake());}async getUsage(sessionId:string){return this.sessions.get(sessionId)?.usage??{estimated:true};}
}
export class CodexCliProvider extends CliProvider{readonly id="codex-cli"as const;readonly name="Codex CLI";readonly command="codex"as const;readonly defaultRoles=["IMPLEMENTER"]as ProviderRole[];readonly setupInstructions="Install Codex CLI and authenticate with `codex login`. ProjectRelay never reads or stores CLI credentials.";protected authCommand(){return{args:["exec","--json","--sandbox","read-only","--skip-git-repo-check","-"],prompt:"Reply with exactly CODEX_OK. Do not read or modify files.",marker:"CODEX_OK"};}protected sessionCommand(session:AgentSession,resume:boolean){const sandbox=session.capability==="WORKSPACE_WRITE"?"workspace-write":"read-only";return resume&&session.externalId?["exec","resume",session.externalId,"--json","--sandbox",sandbox,"-"]:["exec","--json","--sandbox",sandbox,"--skip-git-repo-check","--cd",session.workspace,"-"];}}
const CLAUDE_READ_ONLY_TOOLS=["Read","Glob","Grep","Bash(git status:*)","Bash(git diff:*)","Bash(npm test:*)","Bash(npm run lint:*)","Bash(npm run typecheck:*)","Bash(npm run build:*)"];
export class ClaudeCliProvider extends CliProvider{readonly id="claude-cli"as const;readonly name="Claude CLI";readonly command="claude"as const;readonly defaultRoles=["REVIEWER","VERIFIER"]as ProviderRole[];readonly setupInstructions="Install Claude Code and authenticate with `claude auth login`. ProjectRelay never reads or stores CLI credentials.";protected override supportsCapability(capability:ExecutionCapability){return capability==="READ_ONLY";}protected authCommand(){return{args:["-p","--output-format","json","--permission-mode","dontAsk","--allowedTools","Read","--disallowedTools","Edit","Write"],prompt:"Reply with exactly CLAUDE_OK. Do not use tools or modify files.",marker:"CLAUDE_OK"};}protected override prompt(session:AgentSession,capsule:TaskCapsuleContent){return[`You are a read-only ${session.role}. Never edit, write, install packages, commit, push, reset databases, or run migrations.`,super.prompt(session,capsule)].join("\n\n");}protected sessionCommand(session:AgentSession,resume:boolean){const args=["-p","--verbose","--output-format","stream-json","--permission-mode","dontAsk","--allowedTools",...CLAUDE_READ_ONLY_TOOLS,"--disallowedTools","Edit","Write","NotebookEdit","WebFetch","WebSearch"];if(resume&&session.externalId)args.push("--resume",session.externalId);else args.push("--session-id",session.id);return args;}}
export class ProviderRegistry{private readonly providers=new Map<ProviderId,CodingProvider>();constructor(providers:CodingProvider[]=[new CodexCliProvider(),new ClaudeCliProvider()]){for(const provider of providers)this.providers.set(provider.id,provider);}get(id:string){const provider=this.providers.get(id as ProviderId);if(!provider)throw new Error(`Unknown provider '${id}'.`);return provider;}list(){return[...this.providers.values()];}}
export const providerRegistry=new ProviderRegistry();
