import { EventEmitter } from "node:events";
import { PassThrough } from "node:stream";
import { describe,expect,it } from "vitest";
import { resolveCliExecutable } from "./executable.js";
import { classifyProviderProbe,ClaudeCliProvider,CodexCliProvider,ProviderRegistry } from "./index.js";
const resolver=async(command:"codex"|"claude")=>({command,canonicalPath:`C:\\safe\\${command}.cmd`});
// Mock spawn deliberately ignores executable and argument values.
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function mockSpawn(outputs:string[],codes:number[]=[],options:{hold?:boolean}={}){return ((_:string,_args:string[])=>{const child=new EventEmitter()as any;child.stdout=new PassThrough();child.stderr=new PassThrough();child.stdin=new PassThrough();child.kill=()=>{queueMicrotask(()=>child.emit("close",null));return true;};if(!options.hold){const output=outputs.shift()??"";const code=codes.shift()??0;queueMicrotask(()=>{child.stdout.end(output);child.emit("close",code);});}return child;})as any;}
describe("Windows CLI resolution",()=>{it("resolves canonical .cmd shims without a shell",async()=>{const seen:string[]=[];const resolved=await resolveCliExecutable("codex",{platform:"win32",pathValue:"C:\\bin",accessFile:async candidate=>{seen.push(candidate);if(!candidate.endsWith(".cmd"))throw new Error("missing");},canonicalize:async candidate=>`C:\\canonical\\${candidate.split("\\").pop()}`});expect(seen).toContain("C:\\bin\\codex.cmd");expect(resolved?.canonicalPath).toBe("C:\\canonical\\codex.cmd");});});
describe("provider health probes",()=>{
  it("reports an absent CLI without probing credentials",async()=>{const provider=new CodexCliProvider(mockSpawn([]),async()=>undefined);const health=await provider.refreshHealth();expect(health).toMatchObject({installed:false,authentication:"UNKNOWN",available:false});});
  it("classifies unauthenticated CLI output",async()=>{const provider=new CodexCliProvider(mockSpawn(["authentication required"],[1]),resolver);expect((await provider.probeAuthentication()).authentication).toBe("NOT_AUTHENTICATED");});
  it("recognizes successful Codex and Claude login probes",async()=>{const codex=new CodexCliProvider(mockSpawn(["CODEX_OK"]),resolver);const claude=new ClaudeCliProvider(mockSpawn(['{"result":"CLAUDE_OK"}']),resolver);expect(await codex.testConnection()).toMatchObject({ok:true,markerObserved:true,exitCode:0});expect(await claude.testConnection()).toMatchObject({ok:true,markerObserved:true,exitCode:0});});
  it("captures rate limits and explicit reset timestamps",async()=>{const provider=new ClaudeCliProvider(mockSpawn(['{"error":"rate limit","reset_at":"2030-01-02T03:04:05.000Z"}'],[1]),resolver);const health=await provider.probeAuthentication();expect(health.authentication).toBe("RATE_LIMITED");expect(health.resetAt?.toISOString()).toBe("2030-01-02T03:04:05.000Z");});
  it("does not fabricate quota",async()=>{const provider=new CodexCliProvider(mockSpawn(["CODEX_OK"]),resolver);const health=await provider.probeAuthentication();expect(health.quotaExact).toBe(false);expect(health.remainingPercent).toBeUndefined();expect(health.quotaSource).toBe("CLI_STATUS");});
  it("classifies malformed successful output as unknown",async()=>{const provider=new ClaudeCliProvider(mockSpawn(["not-json and no marker"]),resolver);expect((await provider.probeAuthentication()).authentication).toBe("UNKNOWN");});
  it("classifies timeout without claiming authentication",()=>expect(classifyProviderProbe("",null,"CODEX_AUTH_OK",{timedOut:true,cancelled:false})).toBe("UNKNOWN"));
  it("contains synchronous Windows process-launch failures",async()=>{const provider=new CodexCliProvider((()=>{throw new Error("spawn EPERM");})as any,resolver);const health=await provider.probeAuthentication();expect(health).toMatchObject({authentication:"CLI_ERROR",available:false});});
  it("honors cancellation and does not leak split secrets",async()=>{const controller=new AbortController();const provider=new CodexCliProvider(mockSpawn([],[],{hold:true}),resolver);const pending=provider.probeAuthentication(controller.signal);await new Promise(resolve=>setTimeout(resolve,0));controller.abort();const health=await pending;expect(health.authentication).toBe("UNKNOWN");const redacted=new CodexCliProvider(mockSpawn(["CODEX_OK token=supersecretvalue"]),resolver);expect((await redacted.testConnection()).output).not.toContain("supersecretvalue");});
  it("has stable registry keys",()=>{const registry=new ProviderRegistry([new CodexCliProvider(mockSpawn([]),resolver),new ClaudeCliProvider(mockSpawn([]),resolver)]);expect(registry.get("codex-cli").defaultRoles).toEqual(["IMPLEMENTER"]);expect(registry.get("claude-cli").defaultRoles).toEqual(["REVIEWER","VERIFIER"]);});
  it("uses workspace-write only for Codex sessions granted WORKSPACE_WRITE capability",async()=>{const calls:string[][]=[];const provider=new CodexCliProvider(((command:string,args:string[])=>{calls.push(args);return mockSpawn([""])(command,args);})as any,resolver);const session=await provider.createSession({workspace:"C:\\MVPmultiAI",taskId:"task",capability:"WORKSPACE_WRITE"});await provider.startSession(session,{} as any);expect(calls[0]).toContain("workspace-write");});
  it("uses read-only sandbox for Codex sessions granted READ_ONLY capability",async()=>{const calls:string[][]=[];const provider=new CodexCliProvider(((command:string,args:string[])=>{calls.push(args);return mockSpawn([""])(command,args);})as any,resolver);const session=await provider.createSession({workspace:"C:\\MVPmultiAI",taskId:"task",capability:"READ_ONLY"});await provider.startSession(session,{} as any);expect(calls[0]).toContain("read-only");expect(calls[0]).not.toContain("workspace-write");});
  it("rejects a Claude session that requests workspace-write instead of silently downgrading it",async()=>{const provider=new ClaudeCliProvider(mockSpawn([]),resolver);await expect(provider.createSession({workspace:"C:\\MVPmultiAI",taskId:"task",capability:"WORKSPACE_WRITE"})).rejects.toThrow(/does not support/i);});
  it("accepts a read-only Claude session",async()=>{const provider=new ClaudeCliProvider(mockSpawn([""]),resolver);const session=await provider.createSession({workspace:"C:\\MVPmultiAI",taskId:"task",capability:"READ_ONLY"});expect(session.capability).toBe("READ_ONLY");});
});
