import { createHash } from "node:crypto";
import { prisma } from "./index.js";
const HANDOFF_MAX_BYTES=32_768;
function canonical(value:unknown):string{if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`;if(value&&typeof value==="object")return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${canonical(item)}`).join(",")}}`;return JSON.stringify(value);}
export const handoffChecksum=(value:unknown)=>createHash("sha256").update(canonical(value)).digest("hex");

export const createConversation=(projectId:string,title:string)=>prisma.conversation.create({data:{projectId,title}});
export const listProjectConversations=(projectId:string)=>prisma.conversation.findMany({where:{projectId},orderBy:{updatedAt:"desc"}});
export const getConversationWithDetails=(id:string)=>prisma.conversation.findUnique({where:{id},include:{messages:{orderBy:[{createdAt:"asc"},{id:"asc"}]},providerSessions:{orderBy:[{startedAt:"asc"},{id:"asc"}]},handoffCapsules:{orderBy:{version:"asc"}},routingDecisions:{orderBy:[{createdAt:"asc"},{id:"asc"}]}}});
export const listConversationMessages=(conversationId:string)=>prisma.conversationMessage.findMany({where:{conversationId},orderBy:[{createdAt:"asc"},{id:"asc"}]});
export const createUserMessage=(conversationId:string,content:string,mode:"ASK"|"IMPLEMENT"|"REVIEW"|"CONTINUE"|"VERIFY",taskId?:string)=>prisma.conversationMessage.create({data:{conversationId,role:"USER",mode,content,status:"COMPLETED",...(taskId?{taskId}:{})}});
export const createAssistantMessage=(input:{conversationId:string;providerId:string;providerSessionId:string;mode:"ASK"|"IMPLEMENT"|"REVIEW"|"CONTINUE"|"VERIFY";content:string;handoffCapsuleId?:string;taskId?:string})=>prisma.conversationMessage.create({data:{...input,role:"ASSISTANT",status:"COMPLETED"}});
export const getOrCreateProviderSession=(conversationId:string,providerId:string)=>prisma.$transaction(async tx=>{const existing=await tx.providerSession.findFirst({where:{conversationId,providerId,status:"RUNNING"},orderBy:{startedAt:"desc"}});return existing??tx.providerSession.create({data:{conversationId,providerId,status:"RUNNING",startedAt:new Date()}});});
export const closeProviderSession=(id:string,status:"COMPLETED"|"CANCELLED"|"FAILED")=>prisma.providerSession.update({where:{id},data:{status,endedAt:new Date()}});
export const createRoutingDecision=(conversationId:string,selectedProviderId:string,reason:string,providerHealthSnapshot:object,requestedProviderId?:string)=>prisma.routingDecision.create({data:{conversationId,selectedProviderId,reason,providerHealthSnapshot,...(requestedProviderId?{requestedProviderId}:{})}});
export async function createHandoffCapsule(input:{conversationId:string;fromProviderId:string;toProviderId:string;objective:string;relevantDecisions:object;filesChanged:object;gitBaseline:object;gitDiffSummary:string;tests:object;unresolvedIssues:object;acceptedFindings:object;sourceMessageRange:object}){const bounded={...input,gitDiffSummary:input.gitDiffSummary.slice(0,HANDOFF_MAX_BYTES)};if(Buffer.byteLength(canonical(bounded))>HANDOFF_MAX_BYTES)throw new Error("Handoff capsule exceeds the bounded payload size.");return prisma.$transaction(async tx=>{const version=(await tx.handoffCapsule.count({where:{conversationId:input.conversationId}}))+1;const payload={...bounded,version};return tx.handoffCapsule.create({data:{...payload,checksum:handoffChecksum(payload)}});});}
